name = "glxdg"
version = "0.0.1"

description = "Gleam implentation for XDG Specifications"
licences = ["AGPL-3.0-or-later"]
repository = { type = "github", user = "vascorsd", repo = "glxdg" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
envoy = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
